### ISSUE TITLE
Errors in the log after long work went 

### ISSUE THREAD

**Issue by lyovav** [undeflabs/UASECO#15]
Version 0.9.3 build 2017-05-16

> [2017-05-17 11:37:09] [LocalRecords] Player [killerfred93] finished with [0:13.705] and took the 17. Local Record!
> [2017-05-17 11:37:09] [Dedimania] Player [killerfred93] finished with [0:13.705] and took the 22. Dedimania Record!
> [2017-05-17 11:37:10] [Event] Player Ranking Updated (Players)
> [2017-05-17 11:37:16] [Event] End Playing [1]
> [2017-05-17 11:37:16] [Event] End Turn [1]
> [2017-05-17 11:37:16] [Event] End Round [1]
> [2017-05-17 11:37:16] [Event] Player Ranking Updated (Players)
> [2017-05-17 11:37:17] [Rank] Player [killerfred93] won for the 57. time!
> [2017-05-17 11:37:18] [Event] End Map
> [UASECO Exception] Error returned: "Unable to retrieve validation data." [-1000] at GbxRemote::query() for method "GetValidationReplay" with arguments:
> array(1) {
>   [0]=>
>   string(12) "killerfred93"
> }
> 
> [2017-05-17 11:37:19] [Dedimania] Unable to get validation replay for Player [killerfred93]: skipped [0:13.705]
> [2017-05-17 11:37:21] [Event] Player Ranking Updated (Players)
> [2017-05-17 11:37:21] [Event] Begin Podium
> [2017-05-17 11:37:25] [Event] End Podium
> [2017-05-17 11:37:25] [Event] Begin Channel Progression
> [2017-05-17 11:37:25] [Event] End Channel Progression
> [2017-05-17 11:37:25] [Event] Unloading Map
> [2017-05-17 11:37:25] [Rasp] Calculating ranks for each Player
> [2017-05-17 11:37:30] [Event] Player Ranking Updated (Players)
> [2017-05-17 11:37:30] [Event] End Match [59]
> [2017-05-17 11:37:30] [Event] Begin Match [60]
> [2017-05-17 11:37:36] [Map] Changing from Map [BaBo-LoL-025] to [TM2-A03-Start] [Env: Stadium, Uid: FBDwCMrPYQnRG6u0YkfvuPeko8, Id: 2047]
> [2017-05-17 11:37:36] [Event] Loading Map
> [2017-05-17 11:37:40] [LocalRecords] Current record on Map [TM2-A03-Start] is [0:08.451] and held by Player [doc_me4ik]
> [2017-05-17 11:37:47] [Event] Begin Map
> [2017-05-17 11:37:48] [Event] Begin Round [1]
> [2017-05-17 11:37:48] [Event] Begin Turn [1]
> [2017-05-17 11:37:48] [Event] Begin Playing [1]
> [2017-05-17 11:37:48] [Event] Player Ranking Updated (Players)
> [PHP Notice] Undefined property: stdClass::$tracking on line 1657 in file /opt/total_lol_tm4/UASECO-0.9.2_2017-05-15/plugins/plugin.dedimania.php
> [2017-05-17 11:37:56] [LocalRecords] Player [amnezik.skull] finished with [0:08.768] and took the 111. Local Record!
> [2017-05-17 11:37:57] [Event] Player Ranking Updated (Players)
> [2017-05-17 11:37:59] [LocalRecords] Player [viblosh] finished with [0:09.108] and took the 114. Local Record!
> [2017-05-17 11:38:00] [LocalRecords] Player [killerfred93] finished with [0:08.804] and took the 113. Local Record!
> [2017-05-17 11:38:00] [Event] Player Ranking Updated (Players)
> [2017-05-17 11:38:02] [Event] Player Ranking Updated (Players)
> [2017-05-17 11:38:02] [Event] Player Ranking Updated (Players)
> [2017-05-17 11:38:10] [LocalRecords] Player [killerfred93] finished with [0:08.633] and took the 94. Local Record!
> [2017-05-17 11:38:11] [Event] Player Ranking Updated (Players)
> [2017-05-17 11:38:15] [Event] Player Ranking Updated (Players)
> [2017-05-17 11:38:21] [LocalRecords] Player [olsaan] finished with [0:09.164] and took the 116. Local Record!
> [2017-05-17 11:38:23] [Event] Player Ranking Updated (Players)
> [2017-05-17 11:38:24] [LocalRecords] Player [killerfred93] finished with [0:08.605] and took the 72. Local Record!
> [2017-05-17 11:38:24] [Event] Player Ranking Updated (Players)
> [2017-05-17 11:38:25] [Event] Player Ranking Updated (Players)
> [2017-05-17 11:38:27] [Player] Connection from Player [69711815] from France [Nick: shiina, IP: 78.245.78.29, Rank: 2751, Id: 6342]
> [PHP Notice] Trying to get property of non-object on line 741 in file /opt/total_lol_tm4/UASECO-0.9.2_2017-05-15/plugins/plugin.modescript_handler.php
> [PHP Notice] Trying to get property of non-object on line 741 in file /opt/total_lol_tm4/UASECO-0.9.2_2017-05-15/plugins/plugin.modescript_handler.php
> [PHP Notice] Trying to get property of non-object on line 741 in file /opt/total_lol_tm4/UASECO-0.9.2_2017-05-15/plugins/plugin.modescript_handler.php
> [PHP Notice] Trying to get property of non-object on line 741 in file /opt/total_lol_tm4/UASECO-0.9.2_2017-05-15/plugins/plugin.modescript_handler.php
> [2017-05-17 11:38:29] [Event] Player Ranking Updated (Players)
> [PHP Notice] Trying to get property of non-object on line 741 in file /opt/total_lol_tm4/UASECO-0.9.2_2017-05-15/plugins/plugin.modescript_handler.php
> [PHP Notice] Trying to get property of non-object on line 741 in file /opt/total_lol_tm4/UASECO-0.9.2_2017-05-15/plugins/plugin.modescript_handler.php
> [PHP Notice] Trying to get property of non-object on line 741 in file /opt/total_lol_tm4/UASECO-0.9.2_2017-05-15/plugins/plugin.modescript_handler.php
> [PHP Notice] Trying to get property of non-object on line 741 in file /opt/total_lol_tm4/UASECO-0.9.2_2017-05-15/plugins/plugin.modescript_handler.php
> [2017-05-17 11:38:34] [Event] Player Ranking Updated (Players)
>

**Comment by undeflabs** [comment]
Fixed
