### ISSUE TITLE
[PHP Notice] Trying to get property of non-object on line 959 in file /opt/total_lol_tm4/UASECO-0.9.4_2017-05-30/plugins/plugin.modescript_handler.php

### ISSUE THREAD

**Issue by lyovav** [undeflabs/UASECO#18]
https://1drv.ms/i/s!Aq_8ScOZC7u_mUCJZqMMEKw7AHUY

**Comment by undeflabs** [comment]
Are you sure that you have updated all files? Because I'm pretty sure that error can't happen with the 0.9.4 files. Could you please try to update/override all files in "includes", "plugins" and "uaseco.php" and try again?

**Comment by lyovav** [comment]
in 0.9.4 errors were no longer observed...

**Comment by undeflabs** [comment]
Thanks!

**Comment by undeflabs** [comment]
This report was from 2017 and at that time PHP/7.4 didn't exists: https://www.php.net/supported-versions.php

I assume that the problem here was a missing tag in the `config/modescript_settings.xml` file.
