### ISSUE TITLE
[UASECO Exception] Error returned: "" [0] at GbxRemote::query() for method "SendDisplayManialinkPage"

### ISSUE THREAD

**Issue by lyovav** [undeflabs/UASECO#19]
[UASECO Exception] Error returned: "" [0] at GbxRemote::query() for method "SendDisplayManialinkPage"
 with arguments: array(3) {   [0]=>   string(56832) "<?xml version="1.0" encoding="utf-8" standalone="yes" ?><manialink id="WarmUpInfoWidget" name="WarmUpInfoWidget" version="3"></manialink><manialink id="MultiLapInfoWidget" name="MultiLapInfoWidget" version="3" winning payment temporary off."/></frame><script>

new install from UASECO-0.9.4_2017-05-30.zip + 0.9.5 fix
more on the link
game.ber.te.ua/logs.tar.gz

**Comment by C-Lodder** [comment]
Perhaps name your titles a little better and put the error in the comment so it's easier to read :)

**Comment by undeflabs** [comment]
Found and fixed for 0.9.5, thanks!

**Comment by lyovav** [comment]
Error is beck
[UASECO Exception] Error returned: "" [0] at GbxRemote::query() for method "SendDisplayManialinkPage" with arguments:
more on the link
game.ber.te.ua/logs.tar.gz

**Comment by undeflabs** [comment]
Fixed in https://github.com/undeflabs/UASECO/blob/82cebed8e09a54ac0aa3236184716e98bc6e89ee/plugins/plugin.records_eyepiece.php
