### ISSUE TITLE
command /admin erasethis 

### ISSUE THREAD

**Issue by lyovav** [undeflabs/UASECO#20]
In the past version of xaseco, this command  deleted the card and gave the opportunity to finish it on the server.
Now this command deletes and immediately loads the next map.
Is it so conceived or not worked out?

**Comment by C-Lodder** [comment]
It kind of makes sense to load the next map IMO

**Comment by undeflabs** [comment]
As C-Lodder already wrote, that's the wanted behavior of UASECO, because it doesn't make sense to finish the map and get a local record, that will be deleted after the map change. =)
