### ISSUE TITLE
[PHP Notice] Undefined property: stdClass::$best on line 563 in file /opt/total_lol_tm4/UASECO_work/plugins/plugin.checkpoints.php

### ISSUE THREAD

**Issue by lyovav** [undeflabs/UASECO#22]
Version 0.9.5 build 2017-06-04
On maps more then 15 CPs and online more 20 I got this error...

**Comment by lyovav** [comment]
Strange but simple trips in checkpoints.xml 
```
<time_diff_widget>
enabled>false</enabled>

<count_widget>
<enabled>false</enabled>

<auto_enable_cps>false</auto_enable_cps>

<auto_enable_dedicps>false</auto_enable_dedicps>
```
сaused to an unexpected result - a decline in the performance of the script was not observed when online 40 people, even on my old server hardware.

**Comment by undeflabs** [comment]
I can't see a "сaused to an unexpected result". What exactly happens with this setup?

The "stdClass::$best" has been fixed already (also available at github).

**Comment by lyovav** [comment]
In UASECO-0.9.5_2017-06-08 this error was not detected online 30+

**Comment by undeflabs** [comment]
Please describe the "unexpected result", maybe I can see why that was happened.

**Comment by lyovav** [comment]
It's important for me to keep the performance of the UASECO online 30-40 players on the server оn my old server hardware. Having disabled auto_enable_cps and auto_enable_dedicps I can not fully recreate this situation...

**Comment by undeflabs** [comment]
So we can close this as it seems it's fixed? If not just add a comment again.
