### ISSUE TITLE
Vote window do not close.

### ISSUE THREAD

**Issue by psyche79** [undeflabs/UASECO#28]
After Vote finished, calculating result!
Vote window do not close.

**Comment by C-Lodder** [comment]
I think this only occurs if a vote is placed, then a user with permissions manually restarts the map.

**Comment by psyche79** [comment]
It's not the case.

**Comment by undeflabs** [comment]
This plugin is very buggy at the moment and should not be used.

**Comment by psyche79** [comment]
Remove comment on line 324-326. Vote window closes.
