### ISSUE TITLE
Performance issues with 10+ players on the server

### ISSUE THREAD

**Issue by C-Lodder** [undeflabs/UASECO#31]
When there are 10 players or more on the server, it's has a massive impact of performance. Uaseco takes a long to to respond to actions, such as:

- adding a track to the jukebox
- skipping a track
- etc etc

**Comment by undeflabs** [comment]
Already reported here, please check and [try to help to find the problem](https://forum.maniaplanet.com/viewtopic.php?p=287960#p287960):

https://forum.maniaplanet.com/viewtopic.php?p=287806#p287806
https://forum.maniaplanet.com/viewtopic.php?p=290011#p290011
https://forum.maniaplanet.com/viewtopic.php?f=522&t=43191
https://forum.maniaplanet.com/viewtopic.php?f=522&t=43662

**Comment by C-Lodder** [comment]
Only 2 things I can see worth doing are:

1. Enable slow queries
2. Disable non-required plugins

We're going to try both soon and will report back with an update

**Comment by undeflabs** [comment]
Added some changes to the required plugins which would make it easier to test with non-required plugins: https://forum.maniaplanet.com/viewtopic.php?f=522&t=43942&p=297644#p297644

**Comment by undeflabs** [comment]
Should be fixed with this update: https://github.com/undeflabs/UASECO/commit/8c488d95b7c075a2b4716a67692af71733977920
