### ISSUE TITLE
webrequest error with usagereport and mania karma

### ISSUE THREAD

**Issue by BestNoob** [undeflabs/UASECO#34]
Aktive Codepage: 65001.

Warning: file_get_contents(https://www.UASECO.org/usagereport.php): failed to op
en stream: HTTP request failed!  in X:\XXXXXXXX\Maniaplanet\uasecoValley\web
request.php on line 173

Warning: file_get_contents(http://europe.mania-karma.com/api/maniaplanet-trackma
nia2-v4.php?Action=Ping&login=bestnoobvalley&authcode=XXXXXXXXXXXXXXXXXXXX
XXXXX): failed to open stream: HTTP request failed!  in X:\XXXXXXX\Maniapl
anet\uasecoValley\webrequest.php on line 173

Warning: file_get_contents(https://www.UASECO.org/usagereport.php): failed to op
en stream: HTTP request failed!  in X:\XXXXXXX\Maniaplanet\uasecoValley\web
request.php on line 173

**Comment by undeflabs** [comment]
Is this still happening? Feel free to reopen then and please add the logfile entries.
