### ISSUE TITLE
Config files not included

### ISSUE THREAD

**Issue by BestNoob** [undeflabs/UASECO#35]
You have plugins like forcemod and old plugins (force loadscreen) inside the uaseco package, but no config files and they are also not downloadable, i hoped that they got created by starting server with this plugin but they arent.

**Comment by undeflabs** [comment]
All included plugins in the folder "plugins/thrid-party" are included by accident and are not part of the official release. These will not be included in the next released anymore.

ForceMod, GreetingDude, LazyButtons, NicknameSync and Pay2Play has been released already, see https://www.uaseco.org/plugins/repository.php for details.

The rest are still under development or not functional at all (like ForceLoadscreen, thx nadeo :( ).

**Comment by BestNoob** [comment]
Ah yes i recognized that most of the 3rd party plugin features are already implemented into uaseco.
