### ISSUE TITLE
Disabling tachometer plugin removes tacho completly

### ISSUE THREAD

**Issue by BestNoob** [undeflabs/UASECO#36]
Disabling tachometer plugin removes tacho completly. And there are no alternative tacho templates/designs included.

**Comment by undeflabs** [comment]
Well... the functionality is provided by that plugin and if you disable it... well.. then the Tachometer is gone. Not a bug, just a consequence.

And that only one design is include is related to the fact, that I really like what I did. If nobody else make an other design which he also share with me this situation will not be changed (that soon).

**Comment by BestNoob** [comment]
I found a few designs but i dont like those, so i wonder how i can tweak it how does this plugin work ?
Where can i get a overview over the styles (as example: TextButtonNav) of MP/Uaseco ?

**Comment by undeflabs** [comment]
You can start from "config/tachometer/template_classic.xml" and edit it. The images are mostly PNG files, ingame graphics has not been used (if I remember right).

**Comment by BestNoob** [comment]
Okay ill try, but is there a way to display the standard ?

**Comment by undeflabs** [comment]
Sure, do a "/admin shutdown" to reset to the default HUD settings* and disable plugin.tachometer.php in "config/plugins.xml".

*) Works only with the current 0.9.6 (at least the build 2018-11-16) from github!

**Comment by BestNoob** [comment]
Hmm what do you mean when is 0.9.6 ready for a Stable release ? When you can promise that it will not destroy again my databse i want to let it run on my servers i want to create in the next days. ( i know backups etc. but its always time to spend for fixing and records in between will get lost)
