### ISSUE TITLE
master branch destroys rasp/database !

### ISSUE THREAD

**Issue by BestNoob** [undeflabs/UASECO#37]
after trying master branch 
/admin add MXID 
shows only unknown, maps wont get listed correctly.

Using my BACKUP wont fix the problems, seems MYSQL DATABSE is damaged

**Comment by undeflabs** [comment]
A simple restart fixes the "unknown" problem after using "/admin add MXID", I'm aware of that bug. It happens sometimes for maps that were already added later erase/removed and you add it again. It is still on my to do list.

**Comment by BestNoob** [comment]
> 
> 
> A simple restart fixes the "unknown" problem after using "/admin add MXID", I'm aware of that bug. It happens sometimes for maps that were already added later erase/removed and you add it again. It is still on my to do list.

Nope a restart ( i completly restarted all servers and MYSQL) didnt solved the problem for me, only the reset of my databse fixed this, maybe its just 1x entry to remove and reload but i was lazy and resetted it all.

**Comment by undeflabs** [comment]
Thanks for the files, I'll take a look into them.

**Comment by ItsPhenom** [comment]
Any update on this?

**Comment by undeflabs** [comment]
Sorry, not yet

**Comment by BestNoob** [comment]
> 
> 
> Sorry, not yet

Is this fixed with actual release ?

**Comment by undeflabs** [comment]
I'am not able to reproduce that behavior yet, so I'am still investigating.
Btw.: If it is fixed, this report will be updated and closed. ;)

**Comment by undeflabs** [comment]
The "/admin add ID" and "Unknown" result has been fixed with the https://github.com/undeflabs/UASECO/commit/78a3e09022b2ed26ea57be15112811266420dc6a commit.

Your database export works fine in my MariaDB server, no errors shown. So I consider this problem as fixed or not UASECO related. Feel free to reopen if you can add more details.
