### ISSUE TITLE
Force mod plugin.force_mod.php only working for Admin ?

### ISSUE THREAD

**Issue by BestNoob** [undeflabs/UASECO#38]
Seems that plugin.force_mod.php is only working for admin !?  At least if a skin.gbx file is set as mod it loads without problems for me (master admin) in a few seconds (cleared game cache to test, and filled game cache to approve) its displayed in a running round after respawn.

But for **visitors its doesnt load**, i do not have any errors in logfiles.

**Comment by undeflabs** [comment]
Let us keep talking about this here: https://forum.maniaplanet.com/viewtopic.php?f=522&t=45271
