### ISSUE TITLE
ESC menu voting not doable

### ISSUE THREAD

**Issue by BestNoob** [undeflabs/UASECO#40]
ESC - Voting is not doable (deactivated), but i activated it inside the configs, the only thing changed after, is that the options are no longer greyed out.

**Comment by undeflabs** [comment]
You have to restart the dedicated Server to re-enable the ESC-Voting feature if you have disabled it for a plugin use.

**Comment by BestNoob** [comment]
Nope, thats not the problem/solution, i do most changes by completly closing the server not only /shutdown for uaseco.
