### ISSUE TITLE
mania karma sometimes does not connect

### ISSUE THREAD

**Issue by BestNoob** [undeflabs/UASECO#42]
mania karma sometimes does not connect (happen every 2nd map if map is local not downloaded from mania eXchange)

**Comment by undeflabs** [comment]
Log file entries please.

**Comment by BestNoob** [comment]
On the way. But best thing is to check it yourself by visiting my servers, youre welcome. I recognized that you shouldnt edit the delay/timeout etc. things in config. Standard is the best. But specially my Canyon Server Karma has often timeouts.

**Comment by undeflabs** [comment]
Sorry, I lost some files... please send again (not password protected this time please), if you can. And only if the problem still exists.
