### ISSUE TITLE
loading map thumbnail picture of non MX maps is not working

### ISSUE THREAD

**Issue by BestNoob** [undeflabs/UASECO#43]
loading map thumbnail picture of non MX maps is not working, i set local folder uasecopictures (same as in uaseco config) as workfolder, do nut understand the external http request for this feature, because in info its described that it use same location as set in uaseco.xml

**Comment by undeflabs** [comment]
To use this feature you have to setup a working HTTP server (e.g. Apache, NGIX...) and a folder which is accessibly by HTTP like "http://www.example.com/mapimages/" and "/mapimages/" should be mapped to that folder in where UASECO stores the map images.
