### ISSUE TITLE
Dedimania records wont displayed

### ISSUE THREAD

**Issue by BestNoob** [undeflabs/UASECO#44]
dedimania records wont get displayed/listed also after restarting the map but in records_eyepiece.xml
display_max_records is set to 0 .

**Comment by undeflabs** [comment]
Does the map have records already? Do you see the chat message if you reach a dedimania record? Any logfile entries which may help why dedimania do not work?

**Comment by BestNoob** [comment]
Now its working, but dont ask my for the reason :D

**Comment by undeflabs** [comment]
As it is working now, I close it then.
