### ISSUE TITLE
UASECO using .bak instead of original file wont safe MatchSettings / Tracklist

### ISSUE THREAD

**Issue by BestNoob** [undeflabs/UASECO#46]
Hmm i recognized that UASECO is using and saving a lot of . bak files like (2019-01-01-20-28-16_tracklist_valley.txt) instead of saving inside the determinated tracklist / matchsettings file.

I dk when this happen first. Any idea whats the problem ?

**Comment by undeflabs** [comment]
Just tested, works as it should. UASECO creates a backup (.bak file) for every "/admin writemaplist" call and then writes the MatchSettings file, which has to be configured in "config/UASECO.xml" at <default_maplist>.
