### ISSUE TITLE
Dedimania records not synced manual Upload to Database ?

### ISSUE THREAD

**Issue by BestNoob** [undeflabs/UASECO#47]
Hello,
i recognized that my servers idnt synced the records with Dedimania, and now it is working instantly driven records are listed on dedimania.

The thing is with the release of UASECO 0.9.6 (2019-03-02) this problem got fixed but **without using the new version !**

Did you changed something on your backend ? Or thats fixed within outo updates ? Or was it a problem fixed with the new Server exe file updates ?

And is there a manual export option like for Karma ?

Has to do with my Issue before https://github.com/undeflabs/UASECO/issues/44

**Comment by undeflabs** [comment]
Please use just one portal for reports: https://forum.maniaplanet.com/viewtopic.php?f=522&t=45588

I prefer https://forum.maniaplanet.com/viewforum.php?f=522 because that's the forum with more users as here.
