### ISSUE TITLE
performance upgrades

### ISSUE THREAD

**Issue by AskAlice** [undeflabs/UASECO#48]
Hi, I'm a professional php developer, and I am an admin on a server that has ~6,000 maps on it, any command takes like 5-10 seconds to process, so it's kind of hard to play on the server, map changes take way too long for example. I was wondering where could I start on improving on the performance? I'd love to make some pull requests

**Comment by undeflabs** [comment]
The performance problem has been fixed in 0.9.6, so it seems you are still use 0.9.5.

**Comment by C-Lodder** [comment]
@undeflabs, even though you fixed a big performance issue in 0.9.6, the code still has major room for improvements.

**Comment by undeflabs** [comment]
> the code still has major room for improvements.
Feel free to submit suggestions... changes...

**Comment by undeflabs** [comment]
@AskAlice: I think your problem has been fixed with the upgrade, if not, feel free to reopen this.
