### ISSUE TITLE
Possibilities to add PostgreSQL as database ?

### ISSUE THREAD

**Issue by WinXaito** [undeflabs/UASECO#53]
Hello,

Do you plan in the future to add a possibility to support postgresql databases?

Thanking you for your support

**Comment by undeflabs** [comment]
It think it should be possible to add support to store the database in PostgreSQL with some changes at includes/core/database.class.php (which is extends mysqli). But that's not yet on my todo list. We're currently focused on removing bugs and translation.

Also I'm not familiar with PostgreSQL, which doesn't help to bring this on top on my todo list. =)

If you're interested to contribute that, you're welcome!
