### ISSUE TITLE
Stadium is limited to maxrank 15 in TA for not upgraded servers!

### ISSUE THREAD

**Issue by BestNoob** [undeflabs/UASECO#58]
I adjusted the settings, so why does this message still appear ? is it just a info ?

`[2019-11-12 02:14:10] [Dedimania] dedimaniaEndMapCallbackHandler() - error(s): Warning in method_handler.php(467): Stadium is limited to maxrank 15 in TA for not upgraded servers! For premium accounts, see Dedimania forum and tm2stats page.`

**Comment by undeflabs** [comment]
Yes, that's just an info and comes direct from the dedimania server (maybe to promote that you could/should upgrade your server account to support dedimania... =).
