### ISSUE TITLE
PHP Problem mit php7.4 ?

### ISSUE THREAD

**Issue by Hoerli1337** [undeflabs/UASECO#64]
Nach einem Upgrade von php7.2 auf php7.4 gibts dauerhaft Logs von uaseco.
Hier ein Auszug:
Beim starten:
`[PHP Notice] Undefined index: AUTOSAVE_MAPLIST on line 829 in file /home/gameserver/TM2/MixedMaps/uAseco/uaseco.php
[PHP Notice] Trying to access array offset on value of type null on line 829 in file /home/gameserver/TM2/MixedMaps/uAseco/uaseco.php
[PHP Notice] Undefined index: SERVER_RANK_MIN_RECORDS on line 838 in file /home/gameserver/TM2/MixedMaps/uAseco/uaseco.php
[PHP Notice] Trying to access array offset on value of type null on line 838 in file /home/gameserver/TM2/MixedMaps/uAseco/uaseco.php`
Während es läuft:
`[PHP Notice] Trying to access array offset on value of type null on line 1367 in file /home/gameserver/TM2/LoL/uAseco/plugins/plugin.modescript_handler.php
[PHP Notice] Undefined index: POS on line 1372 in file /home/gameserver/TM2/LoL/uAseco/plugins/plugin.modescript_handler.php
[PHP Notice] Trying to access array offset on value of type null on line 413 in file /home/gameserver/TM2/MixedMaps/uAseco/includes/core/player.class.php`

Das System an sich läuft durch und stürzt irgendwann mal ab. Bei mir lief es jetzt etwa 2 Tage durch, dann ist es gecrasht.
Falls noch mehr Logs erwünscht sind, kann ich diese gerne posten :)

________________________________________

uaseco 0.9.7
________________________________________
`PHP 7.4.2 (cli) (built: Jan 23 2020 11:21:30) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies with Zend OPcache v7.4.2, Copyright (c), by Zend Technologies`

________________________________________

Problem trat scheinbar schon mal auf :S 
[https://github.com/undeflabs/UASECO/issues/18](https://github.com/undeflabs/UASECO/issues/18)

**Comment by undeflabs** [comment]
> `[PHP Notice] Undefined index: AUTOSAVE_MAPLIST on line 829 in file uAseco/uaseco.php`
> `[PHP Notice] Trying to access array offset on value of type null on line 829 in file uAseco/uaseco.php`

You forgot to add <autosave_maplist> on updating: https://github.com/undeflabs/UASECO/blob/master/newinstall/config/UASECO.xml#L67



> `[PHP Notice] Undefined index: SERVER_RANK_MIN_RECORDS on line 838 in file uAseco/uaseco.php`
`[PHP Notice] Trying to access array offset on value of type null on line 838 in file uAseco/uaseco.php`

Same here for <server_rank_min_records>: https://github.com/undeflabs/UASECO/blob/master/newinstall/config/UASECO.xml#L80


> `[PHP Notice] Trying to access array offset on value of type null on line 1367 in file uAseco/plugins/plugin.modescript_handler.php`
`[PHP Notice] Undefined index: POS on line 1372 in file uAseco/plugins/plugin.modescript_handler.php`

These are strange, do your `config/modescript_settings.xml` tags `<checkpoint_list>` and `<chrono>` looks like this:

```
<checkpoint_list>
	<visible>true</visible>
	<pos>
		<x>48.0</x>
		<y>-52.0</y>
		<z>5.0</z>
	</pos>
</checkpoint_list>

<chrono>
	<visible>true</visible>
	<pos>
		<x>0.0</x>
		<y>-80.0</y>
		<z>5.0</z>
	</pos>
</chrono>
```



`[PHP Notice] Trying to access array offset on value of type null on line 413 in file uAseco/includes/core/player.class.php`

This has been fixed, but has not yet been send to github.

 
> Das System an sich läuft durch und stürzt irgendwann mal ab. Bei mir lief es jetzt etwa 2 Tage durch, dann ist es gecrasht.

Please post the logfile where the crash occured.


 
> Problem trat scheinbar schon mal auf :S
> #18

That report was from 2017 and at that time PHP/7.4 didn't exists: https://www.php.net/supported-versions.php

**Comment by Hoerli1337** [comment]
1 + 2 is fixed :)

`config/modescript_settings.xml`
I have 1:1 the same config. Never change anything there.

After the fix for problem 1 and 2 i got this new errors:
`[PHP Notice] Trying to access array offset on value of type null on line 1296 in file /home/gameserver/TM2/LoL/uAseco/includes/core/helper.class.php
[PHP Notice] Undefined index: CHAT_PREFIX_REPLACEMENT on line 1296 in file /home/gameserver/TM2/EnvironmentMixing/uAseco/includes/core/helper.class.php
[PHP Notice] Trying to access array offset on value of type bool on line 5008 in file /home/gameserver/TM2/LoL/uAseco/plugins/plugin.records_eyepiece.php`

I wait now for a crash, to post the log.
Is running right now, he's just spamming like crazy.

**Comment by undeflabs** [comment]
> After the fix for problem 1 and 2 i got this new errors:
> `[PHP Notice] Trying to access array offset on value of type null on line 1296 in file includes/core/helper.class.php [PHP Notice] Undefined index: CHAT_PREFIX_REPLACEMENT on line 1296 in file includes/core/helper.class.php`

This will fix it: https://github.com/undeflabs/UASECO/blob/master/newinstall/config/UASECO.xml#L159


> `[PHP Notice] Trying to access array offset on value of type bool on line 5008 in file plugins/plugin.records_eyepiece.php`
> 
> Is running right now, he's just spamming like crazy.

Well, yes... with PHP/7.4 UASECO needs some adjustments... I've already done them, but I can't update github right now, because I (or better "we") made too much changes which we decided to release with a public 0.9.7 release instead of updating github before.

**Comment by Hoerli1337** [comment]
> This will fix it: https://github.com/undeflabs/UASECO/blob/master/newinstall/config/UASECO.xml#L159
Jep, fixed! :)

Now i wait for the next update, that fix the rest.

**Comment by undeflabs** [comment]
Just pushed an update to support the PHP/7.4.x
