### ISSUE TITLE
Codelines removed but not replaced ?!

### ISSUE THREAD

**Issue by BestNoob** [undeflabs/UASECO#65]
https://github.com/undeflabs/UASECO/archive/master.zip

You removed code and textlines but didnt replaced those. So theyre just removed and no longer appear ingame. As example the donation plugin.

Must be a mistake ..... and you removed codelines/text in 4 files.

**Comment by undeflabs** [comment]
The meantioned donation plugin has being changed already 7 months ago, please add more details.

**Comment by BestNoob** [comment]
U have changed 4 files in compare to 0.9.6
WinMerge directly shows this ^^ (very useful tool to compare)
One is the donationplugin mesage you removed the lines and so when someone is donating .... no message is printed out in chat or personally to the donating player.

**Comment by undeflabs** [comment]
Compared to 0.9.6 we made tons of changes to the current 0.9.7 at github and not just 4 files.

About plugin.donate.php you can see every change here: https://github.com/undeflabs/UASECO/commits/master/plugins/plugin.donate.php

We (more ACA then me) are working on translations which means that the messages in the plugins are moved into the corresponding `locales/plugin.donate.xml` file. This has also been documented in the `docs/CHANGELOG.md`:

https://github.com/undeflabs/UASECO/blob/master/docs/CHANGELOG.md
> Added newinstall/locales/plugin.donate.xml [aca]

**Comment by BestNoob** [comment]
Dude dont close it so fast.  There might be following: the ürovided link to master branch is broken/wrong so that ive downloaded a ndifferent master branch than the actual one (used the link from your official website) 

And the other thing is that the donation plugin is not working !! in actual master branch. Doesnt natter you changed the location of the translation it just dont show the donation message and isnt working.

And this is not the only problem. (but might be issued with wrong master branch ?!)

**Comment by undeflabs** [comment]
The links I provided are working for me. Anyway there is only one master branch. The link you provided in your first report is the same link to the master branch I provide at my official website.

Just tested the plugin.donate.php from Github and it works fine for me.

If it doesn't show any messages, then you probably forgot you copy the locale files.
