### ISSUE TITLE
Issue in helper.class.php when using addManialink function

### ISSUE THREAD

**Issue by psadaic** [undeflabs/UASECO#7]
[PHP Warning] explode() expects parameter 2 to be string, array given on line 501 in file /home/servers/ManiaPlanet/uasecodev/UASECO-development/includes/core/helper.class.php
[PHP Warning] Invalid argument supplied for foreach() on line 501 in file /home/servers/ManiaPlanet/uasecodev/UASECO-development/includes/core/helper.class.php

Issue occurs when sending manialink to a list of logins. I've avoided the problem by just looping the login array and sending to players 1 by 1 but just letting you know about this issue.

**Comment by undeflabs** [comment]
Fixed for the next developer branch update. Thanks!
