### ISSUE TITLE
Plugins can't store a SimpleXML Object in $this->someProperty

### ISSUE THREAD

**Issue by askuri** [undeflabs/UASECO#9]
If debug mode is enabled, line 538 in uaseco.php serializes $aseco->plugins, which can't be done with SimpleXML Objects. PHP throws an exception.

**Comment by undeflabs** [comment]
Just tested it with enabled debug mode under Linux with all Plugins (RASP Karma and RASP Votes and ManiaKarma and VoteManager):

» NbMaps:          234 :    274.084 bytes
» NbPlayers:         2 :      6.704 bytes
» PlayerRanks:       2 :        553 bytes
» NbPlugins:        49 :  6.476.391 bytes
» RegEvents:        50 :  6.495.684 bytes
» RegChatCmds:     109 :  6.439.136 bytes

As you see at the "NbPlugins" line, no exception.
Btw.: It was line 537.

**Comment by askuri** [comment]
Did you store some SimpleXML objects in the plugin classes for testing?

**Comment by undeflabs** [comment]
No, because the current available plugins are not using it. Please provide a plugin for tests then.

**Comment by undeflabs** [comment]
Just made myself one plugin and can reproduce the problem, i have think about a possible solution now.
